/*
 * FrameworkCommitEvent.java
 *
 * OpenCOMJ is a flexible component model for reconfigurable reflection developed at Lancaster University.
 * Copyright (C) 2005 Paul Grace
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License 
 * as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program; if not, 
 * write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

package OpenCOM.Events;
import OpenCOM.*;
import java.util.*;
/**
 * Event generated by the kernel to indicate that a framework has commited its reconfiguration.
 *
 * @author  Paul Grace
 * @version 1.3.5
 */
public class FrameworkCommitEvent {
    public String FrameworkName;
    public Vector<IUnknown>  m_ppComps;
    
    /** Creates a new instance of the FrameworkCommit event */
    public FrameworkCommitEvent(String fName, Vector<IUnknown> comps) {
        FrameworkName=fName;
        m_ppComps = comps;
    }

}
